name: dart_state_machine
description: A general purpose finite-state machine for Dart developers.
version: 0.3.2
homepage: https://github.com/vitkhudenko/dart_state_machine

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.5
  mockito: ^5.0.0
